# Generated by Django 4.2.3 on 2023-07-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashing',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
